---
- name: "install xhprof"
  command: pecl install xhprof-{{ xhprof_version }}
  register: xhprof_result
  changed_when: "'already installed' not in xhprof_result.stdout"
  failed_when: "xhprof_result.stderr"

- name: "copy default vhost"
  copy: src=xhprof.conf dest=/etc/apache2/sites-available/xhprof.conf

- name: "enable xhprof vhosts"
  shell: a2ensite xhprof.conf
  register: a2ensite_result
  changed_when: "'Enabling xhprof' in a2ensite_result.stdout"
  notify: restart webserver

- name: "Copy pubstack_xhprof init script"
  copy: src=pubstack_xhprof dest=/etc/init.d/pubstack_xhprof mode=0755

- name: "Ensure xhprof init script runs on start up"
  command: update-rc.d pubstack_xhprof defaults

- name: "Run the xhprof init script once now"
  command: /etc/init.d/pubstack_xhprof
  args:
    creates: /tmp/xhprof

- name: "Adding XHProf to Pubstack Tools"
  replace: dest=/var/www/pubstack/index.php regexp='(<!-- tools -->)' replace='<li><a href="http://xhprof.pubstack.dev">XHProf</a></li><!-- tools -->'
